### ISSUE TITLE
Sync service died in listen.py

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#151]
```
[2018-04-12 08:43:26,842] WARNING:sync.listen:Traceback (most recent call last):
  File "/app/wpt-sync/sync/listen.py", line 52, in listen_forever
    self._conn.drain_events(timeout=1.0)
  File "/app/venv/lib/python2.7/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/app/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/app/venv/lib/python2.7/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/app/venv/lib/python2.7/site-packages/amqp/connection.py", line 476, in blocking_read
    frame = self.transport.read_frame()
  File "/app/venv/lib/python2.7/site-packages/amqp/transport.py", line 226, in read_frame
    frame_header = read(7, True)
  File "/app/venv/lib/python2.7/site-packages/amqp/transport.py", line 346, in _read
    s = recv(n - len(rbuf))  # see note above
  File "/usr/local/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
error: [Errno 110] Connection timed out
```

**Comment by mjzffr** [comment]
@jgraham Judging by rest of the the logs, it didn't actually die, right? The retry worked in all cases and the tasks continued. 

You restarted it today to deploy a bug fix, but did you actually find that the docker container was stopped today at any point?

**Comment by jgraham** [comment]
Ah, you might be right.

I got an email `Warning: your queue "queue/wptsync/wpt-sync-prod/treeherder-jobs" […] is
overgrowing (4153 ready messages, 4153 total messages).`, which I took to mean something had stopped working.

Although there were also some similar emails about treeherder-prototype jobs queues at the same time, so maybe it was a false alarm?

**Comment by mjzffr** [comment]
Closing for now. Feel free to reopen. (In the mean time, I did find some interesting ideas about managing these connection errors more robustly. kombu has a ConsumerMixin that can take care of various edge cases for us, for example.)
