### ISSUE TITLE
Repeatedly setting and unsetting the error whiteboard flag in Bugzilla

### ISSUE THREAD

**Issue by mjzffr** [mozilla/wpt-sync#64]
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1439356

**Comment by jgraham** [comment]
13:17 < jgraham> So I think what's happening is that various events retrigger the code and the first thing we do is unset the error flag, then try to do some stuff and then get the same error 
13:17 < jgraham> But bz is updated synchronously
13:17 < jgraham> So there are two options
13:18 < jgraham> I think the easiest thing to do is to unset the error flag only if the command completes without an error
13:18 < jgraham> But that's a bit messy because there's no clear entry point
13:19 < jgraham> The other option is to rework the way we interact with bugzilla so that there's a local state that gets updated and we only update the actual bug at the end of each session
13:19 < jgraham> Which seems conceptually nice, but also like it will be more effort

**Comment by mjzffr** [comment]
In this particular case, git apply keeps failing after a pr status change.

```
Feb 23 07:26:06 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:06,175] INFO:sync.load:Got sync <DownstreamSync downstream sync/downstream/open/9570> for PR 9570
Feb 23 07:26:06 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:06,176] INFO:sync.base:Called entry point sync.downstream.status_changed
Feb 23 07:26:06 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:06,177] DEBUG:sync.base:Called args (<git.Repo "/app/repos/gecko">, <git.Repo "/app/repos/web-platform-tests">, <DownstreamSync downstream sync/downstream/open/9570>, u'continuous-integration/travis-ci/pr', u'pending', u'https://travis-ci.org/w3c/web-platform-tests/builds/345227001?utm_source=github_status&utm_medium=notification', u'92fad2731767105e6b6f978c4e4c6585ea20dd3c') kwargs {}
Feb 23 07:26:06 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:06,177] INFO:sync.gitutils:Fetching mozilla-unified
Feb 23 07:26:06 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:06,178] DEBUG:git.cmd:Popen(['git', 'fetch', 'mozilla'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:08 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:08,340] INFO:sync.gitutils:Fetching web-platform-tests
Feb 23 07:26:08 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:08,341] DEBUG:git.cmd:Popen(['git', 'fetch', 'origin'], cwd=/app/repos/web-platform-tests, universal_newlines=False, shell=None)
Feb 23 07:26:10 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:10,052] DEBUG:sync.downstream:Got status pending for PR 9570
Feb 23 07:26:10 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:10,277] DEBUG:sync.downstream:PR 9570 gecko HEAD was e855644981bd8d9317a292c6894c2af968840031
Feb 23 07:26:10 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:10,279] DEBUG:git.cmd:Popen(['git', 'rev-list', '--reverse', '4a5533d4737eff427aa28bcba3d76389ddd4a5af..e855644981bd8d9317a292c6894c2af968840031', '--'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:10 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:10,481] INFO:sync.downstream:Retaining 0 previous commits
Feb 23 07:26:10 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:10,481] INFO:sync.downstream:Resetting gecko to latest central
Feb 23 07:26:10 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:10,494] DEBUG:git.cmd:Popen(['git', 'rev-list', '--reverse', 'aa7041bbd31b1a67759161e52ec680e200140e22..92fad2731767105e6b6f978c4e4c6585ea20dd3c', '--'], cwd=/app/repos/web-platform-tests, universal_newlines=False, shell=None)
Feb 23 07:26:10 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:10,707] DEBUG:git.cmd:Popen(['git', 'reset', '--hard', 'sync/downstream/open/9570'], cwd=/app/workspace/work/gecko/downstream/9570, universal_newlines=False, shell=None)
Feb 23 07:26:24 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:24,174] INFO:sync.downstream:Moving commit 92fad2731767105e6b6f978c4e4c6585ea20dd3c
Feb 23 07:26:24 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:24,176] DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=/app/repos/web-platform-tests, universal_newlines=False, shell=None)
Feb 23 07:26:24 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:24,385] DEBUG:git.cmd:Popen(['git', 'show', '--binary', '--pretty=email', '92fad2731767105e6b6f978c4e4c6585ea20dd3c'], cwd=/app/repos/web-platform-tests, universal_newlines=False, shell=None)
Feb 23 07:26:24 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:24,593] DEBUG:git.cmd:Popen(['git', 'update-index', '--refresh'], cwd=/app/workspace/work/gecko/downstream/9570, universal_newlines=False, shell=None)
Feb 23 07:26:25 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:25,146] DEBUG:git.cmd:Popen(['git', 'apply', '--binary', '--directory=testing/web-platform/tests', '--index', '-p', '1', '--reject', '/app/workspace/work/gecko/downstream/9570/92fad2731767105e6b6f978c4e4c6585ea20dd3c.diff'], cwd=/app/workspace/work/gecko/downstream/9570, universal_newlines=False, shell=None)
Feb 23 07:26:25 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:25,507] DEBUG:git.cmd:Popen(['git', 'read-tree', '--empty'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:25 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:25,704] DEBUG:git.cmd:Popen(['git', 'hash-object', '--path=data', '--stdin', '-w'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:25 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:25,904] DEBUG:git.cmd:Popen(['git', 'update-index', '--add', '--cacheinfo', '100644', 'f86be2e0041050bf12057adcfcc4eab8d33cd46c\n', 'data'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:26 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:26,100] DEBUG:git.cmd:Popen(['git', 'write-tree'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:26 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:26,296] DEBUG:git.cmd:Popen(['git', 'commit-tree', '-m', 'Update error', '-p', 'refs/syncs/sync/downstream/open/9570', '55325b6504a33dbe29eafcf1a498e2d3567293fc'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:26 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:26,495] DEBUG:git.cmd:Popen(['git', 'read-tree', '--empty'], cwd=/app/repos/gecko, universal_newlines=False, shell=None)
Feb 23 07:26:26 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:26,699] DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): bugzilla.mozilla.org
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:27,883] DEBUG:urllib3.connectionpool:https://bugzilla.mozilla.org:443 "PUT /rest/bug/1439356 HTTP/1.1" 200 None
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:27,886] DEBUG:urllib3.connectionpool:Resetting dropped connection: bugzilla.mozilla.org
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,550] DEBUG:urllib3.connectionpool:https://bugzilla.mozilla.org:443 "GET /rest/bug/1439356?include_fields=version&include_fields=id&include_fields=summary&include_fields=status&include_fields=op_sys&include_fields=resolution&include_fields=product&include_fields=component&include_fields=platform&include_fields=whiteboard HTTP/1.1" 200 None
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,552] WARNING:celery.redirected:Traceback (most recent call last):
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,552] WARNING:celery.redirected:File "sync/downstream.py", line 445, in status_changed
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,553] WARNING:celery.redirected:sync.update_commits()
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,553] WARNING:celery.redirected:File "sync/downstream.py", line 254, in update_commits
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,553] WARNING:celery.redirected:self.wpt_to_gecko_commits()
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,553] WARNING:celery.redirected:File "sync/downstream.py", line 309, in wpt_to_gecko_commits
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,554] WARNING:celery.redirected:metadata=metadata)
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,554] WARNING:celery.redirected:File "sync/commit.py", line 191, in move
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,554] WARNING:celery.redirected:raise AbortError(err_msg)
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,554] WARNING:celery.redirected:AbortError: git apply failed
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:         ['git', 'apply', '--binary', '--directory=testing/web-platform/tests', '--index', '-p', '1', '--reject', '/app/workspace/work/gecko/downstream/9570/92fad2731767105e6b6f978c4e4c6585ea20dd3c.diff'] returned status 1
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:         Patch saved as :/app/workspace/work/gecko/downstream/9570/92fad2731767105e6b6f978c4e4c6585ea20dd3c.diff
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:         Commit message saved as: /app/workspace/work/gecko/downstream/9570/92fad2731767105e6b6f978c4e4c6585ea20dd3c.message
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:   stderr: 'Checking patch testing/web-platform/tests/mediacapture-streams/MediaStreamTrack-getCapabilities.https.html...
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: error: testing/web-platform/tests/mediacapture-streams/MediaStreamTrack-getCapabilities.https.html: does not exist in index'
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: [2018-02-23 12:26:28,555] ERROR:sync.downstream:git apply failed
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:         ['git', 'apply', '--binary', '--directory=testing/web-platform/tests', '--index', '-p', '1', '--reject', '/app/workspace/work/gecko/downstream/9570/92fad2731767105e6b6f978c4e4c6585ea20dd3c.diff'] returned status 1
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:         Patch saved as :/app/workspace/work/gecko/downstream/9570/92fad2731767105e6b6f978c4e4c6585ea20dd3c.diff
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:         Commit message saved as: /app/workspace/work/gecko/downstream/9570/92fad2731767105e6b6f978c4e4c6585ea20dd3c.message
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log:   stderr: 'Checking patch testing/web-platform/tests/mediacapture-streams/MediaStreamTrack-getCapabilities.https.html...
Feb 23 07:26:28 ip-172-31-9-38_wptsync_host sync.log: error: testing/web-platform/tests/mediacapture-streams/MediaStreamTrack-getCapabilities.https.html: does not exist in index' 
```
